In [1]:
import numpy as np 
import matplotlib.pyplot as plt 


In [23]:
input_size = 4
hidden_size = 10
num_classes = 3
num_inputs = 5
std = 1e-1
output_size= 3

#def init_toy_model():
#    np.random.seed(0)
#    return TwoLayerNet(input_size, hidden_size, num_classes, std=1e-1)

def init_toy_data():
    np.random.seed(1)
    X = 10 * np.random.randn(num_inputs, input_size)
    y = np.array([0, 1, 2, 2, 1])
    return X, y

#net = init_toy_model()
X, y = init_toy_data()

In [24]:
X.shape

(5, 4)

In [25]:
params = std * np.random.randn(input_size, hidden_size)

In [26]:
params.shape

(4, 10)

In [27]:
N, D = X.shape

In [28]:
W1 = std * np.random.randn(input_size, hidden_size)
b1 = np.zeros(hidden_size)
W2 = std * np.random.randn(hidden_size, output_size)
b2 = np.zeros(output_size)

In [30]:
step1 = np.dot(X, W1) + b1

In [47]:
step1

array([[-1.51093074,  2.25106852,  1.03940399, -0.55144768,  0.04129802,
         0.96849953,  2.7486483 ,  1.71599202,  4.01026625, -4.08008554],
       [ 1.37027675,  1.75406198,  0.68674588, -1.07283956, -0.28004985,
         4.73754991,  0.77562543,  0.0352369 ,  2.0463458 , -1.52294679],
       [-2.67557051, -0.14946547,  1.16964886,  1.60182044, -0.50537598,
         0.49483881,  0.16519853,  0.74063198,  2.09531002, -0.42217677],
       [-0.77289909, -0.64146923,  0.39744991,  0.92705179, -0.51969921,
         0.8508635 , -0.62943255, -0.42788387,  0.02701475,  0.67041573],
       [ 2.08716922,  0.32625702, -0.43977978, -1.07270463, -0.10612718,
         1.83833582, -0.15503538, -0.94755651, -0.93504884,  0.02636087]])

In [66]:
for inx, el in enumerate(step1, 0):
    for ind2 , el2 in enumerate(el, 0):
        if el2 < 0:
            step1[inx][ind2] = 0

In [68]:
step1

array([[0.        , 2.25106852, 1.03940399, 0.        , 0.04129802,
        0.96849953, 2.7486483 , 1.71599202, 4.01026625, 0.        ],
       [1.37027675, 1.75406198, 0.68674588, 0.        , 0.        ,
        4.73754991, 0.77562543, 0.0352369 , 2.0463458 , 0.        ],
       [0.        , 0.        , 1.16964886, 1.60182044, 0.        ,
        0.49483881, 0.16519853, 0.74063198, 2.09531002, 0.        ],
       [0.        , 0.        , 0.39744991, 0.92705179, 0.        ,
        0.8508635 , 0.        , 0.        , 0.02701475, 0.67041573],
       [2.08716922, 0.32625702, 0.        , 0.        , 0.        ,
        1.83833582, 0.        , 0.        , 0.        , 0.02636087]])

In [69]:
step2 = np.dot(step1, W2) + b2

In [70]:
step2

array([[-0.48288681,  0.4738051 ,  0.83893654],
       [-0.8239538 ,  0.18107553, -0.36066668],
       [-0.4012836 ,  0.02669508,  0.42571644],
       [-0.06155891, -0.24555372, -0.05656703],
       [-0.31430811,  0.2095783 , -0.20501561]])