In [2]:
import numpy as np 
import matplotlib.pyplot as plt 


In [276]:
input_size = 4
hidden_size = 10
num_classes = 3
num_inputs = 5
std = 1e-1
output_size= 3

#def init_toy_model():
#    np.random.seed(0)
#    return TwoLayerNet(input_size, hidden_size, num_classes, std=1e-1)

def init_toy_data():
    np.random.seed(1)
    X = 10 * np.random.randn(num_inputs, input_size)
    y = np.array([0, 1, 2, 2, 1])
    return X, y

#net = init_toy_model()
X, y = init_toy_data()

In [277]:
y

array([0, 1, 2, 2, 1])

In [4]:
X.shape

(5, 4)

In [5]:
params = std * np.random.randn(input_size, hidden_size)

In [6]:
params.shape

(4, 10)

In [7]:
N, D = X.shape

In [60]:
N , D

(5, 4)

In [70]:
np.random.seed(0)
W1 = std * np.random.randn(input_size, hidden_size)
b1 = np.zeros(hidden_size)
W2 = std * np.random.randn(hidden_size, output_size)
b2 = np.zeros(output_size)

In [197]:
b1.shape

(10,)

In [143]:
W1.shape

(4, 10)

In [142]:
X.shape

(5, 4)

In [208]:
Z_3 = []
for i in range(len(X)):
    xi = X[i,:]
    z_2 = np.dot(W1.T, xi ) + b1
    z_2[z_2 < 0] = 0
    a_2 = z_2
    z_3 = np.dot(W2.T, a_2) + b2
    Z_3.append(z_3)
    
print(Z_3) 

[array([-0.81233741, -1.27654624, -0.70335995]), array([-0.17129677, -1.18803311, -0.47310444]), array([-0.51590475, -1.01354314, -0.8504215 ]), array([-0.15419291, -0.48629638, -0.52901952]), array([-0.00618733, -0.12435261, -0.15226949])]


In [211]:
step1 = np.dot(X, W1) + b1

In [213]:
step1
step1[step1 < 0] = 0
step1

array([[3.95947405, 0.        , 1.62023427, 6.08287206, 1.93650153,
        0.        , 0.        , 0.        , 0.        , 0.73773989],
       [0.        , 0.        , 1.27951663, 1.87210399, 4.81975823,
        0.        , 0.        , 0.        , 2.15938324, 5.11493888],
       [0.        , 0.        , 3.21533801, 3.68018447, 4.52051191,
        0.        , 0.        , 0.        , 2.92803574, 3.11513047],
       [0.        , 0.        , 1.34869732, 0.56798438, 2.18344354,
        0.        , 0.        , 0.        , 2.07688014, 2.1940494 ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.8990617 , 0.        , 0.56481687]])

In [214]:
W2

array([[-0.1048553 , -0.14200179, -0.17062702],
       [ 0.19507754, -0.05096522, -0.04380743],
       [-0.12527954,  0.07774904, -0.16138978],
       [-0.02127403, -0.08954666,  0.03869025],
       [-0.05108051, -0.11806322, -0.00281822],
       [ 0.04283319,  0.00665172,  0.03024719],
       [-0.06343221, -0.03627412, -0.06724604],
       [-0.03595532, -0.08131463, -0.17262826],
       [ 0.01774261, -0.04017809, -0.16301983],
       [ 0.04627823, -0.09072984,  0.00519454]])

In [217]:
scores = np.dot(relu,W2) + b2

In [292]:
scores

array([[-0.81233741, -1.27654624, -0.70335995],
       [-0.17129677, -1.18803311, -0.47310444],
       [-0.51590475, -1.01354314, -0.8504215 ],
       [-0.15419291, -0.48629638, -0.52901952],
       [-0.00618733, -0.12435261, -0.15226949]])

In [285]:
X_norm = np.apply_along_axis(lambda x: np.exp(x) / np.sum(np.exp(x)),1, scores)

In [286]:
new_norm = -np.log(X_norm)
new_norm

array([[1.0093327 , 1.47354153, 0.90035523],
       [0.74253431, 1.75927064, 1.04434198],
       [0.84313862, 1.34077701, 1.17765537],
       [0.8774757 , 1.20957917, 1.25230231],
       [1.01255895, 1.13072424, 1.15864112]])

In [287]:
j2 = np.mean(new_norm[np.arange(len(y)), y])
j2

1.2658570521180532

In [237]:
J = []
for i, score in enumerate(numerator):
    
    score_i = score[y[i]]/ denom[i]
    print(score_i)
    log_score_i = -np.log(score_i) 
    
    J.append(log_score_i)

JJ = np.mean(J)

0.3644621041023232
0.1721703914527796
0.3080000394524406
0.2858459326005048
0.32279938820296766


In [288]:
print(J)
print(JJ)

[1.0093326997358134, 1.7592706445552908, 1.1776553679162312, 1.252302310512784, 1.1307242378701479]
1.2658570521180532


In [289]:
# take square of differences and sum them
l2 = np.sum(np.power((W1),2)) + np.sum(np.power((W2),2))
l2 = 0.05* l2
print(l2)

0.03793083921176699


In [290]:
loss = j2 + l2  #1.66 0.75

In [291]:
correct_loss = 1.30378789133
print('Difference between your loss and correct loss:')
print(np.sum(np.abs(loss - correct_loss)))

Difference between your loss and correct loss:
1.7985612998927536e-13
