In [2]:
import numpy as np 
import matplotlib.pyplot as plt 


In [3]:
input_size = 4
hidden_size = 10
num_classes = 3
num_inputs = 5
std = 1e-1
output_size= 3

#def init_toy_model():
#    np.random.seed(0)
#    return TwoLayerNet(input_size, hidden_size, num_classes, std=1e-1)

def init_toy_data():
    np.random.seed(1)
    X = 10 * np.random.randn(num_inputs, input_size)
    y = np.array([0, 1, 2, 2, 1])
    return X, y

#net = init_toy_model()
X, y = init_toy_data()

In [184]:
y

array([0, 1, 2, 2, 1])

In [4]:
X.shape

(5, 4)

In [5]:
params = std * np.random.randn(input_size, hidden_size)

In [6]:
params.shape

(4, 10)

In [7]:
N, D = X.shape

In [60]:
N , D

(5, 4)

In [70]:
np.random.seed(0)
W1 = std * np.random.randn(input_size, hidden_size)
b1 = np.zeros(hidden_size)
W2 = std * np.random.randn(hidden_size, output_size)
b2 = np.zeros(output_size)

In [143]:
W1.shape

(4, 10)

In [142]:
X.shape

(5, 4)

In [164]:
step1 = np.dot(X, W1) + b1

In [165]:
step1

array([[ 3.95947405, -0.99064704,  1.62023427,  6.08287206,  1.93650153,
        -1.19116687, -0.71497239, -1.31160012, -0.7531654 ,  0.73773989],
       [-3.37733121, -2.14818616,  1.27951663,  1.87210399,  4.81975823,
        -4.27031636, -3.47313279, -0.90066642,  2.15938324,  5.11493888],
       [-3.52507871, -0.058394  ,  3.21533801,  3.68018447,  4.52051191,
        -2.84353882, -2.53713173, -2.74788314,  2.92803574,  3.11513047],
       [-3.68900855, -0.3624225 ,  1.34869732,  0.56798438,  2.18344354,
        -1.6339401 , -2.18143879, -1.40711833,  2.07688014,  2.1940494 ],
       [-0.44808779, -1.09765407, -1.31776936, -1.67897452, -0.8186224 ,
        -0.09468021, -0.75644817,  0.8990617 , -0.41806688,  0.56481687]])

In [168]:
#ReLU
for inx, el in enumerate(step1, 0):
    for ind2 , el2 in enumerate(el, 0):
        if el2 < 0:
            step1[inx][ind2] = 0

In [169]:
relu

array([[3.95947405, 0.        , 1.62023427, 6.08287206, 1.93650153,
        0.        , 0.        , 0.        , 0.        , 0.73773989],
       [0.        , 0.        , 1.27951663, 1.87210399, 4.81975823,
        0.        , 0.        , 0.        , 2.15938324, 5.11493888],
       [0.        , 0.        , 3.21533801, 3.68018447, 4.52051191,
        0.        , 0.        , 0.        , 2.92803574, 3.11513047],
       [0.        , 0.        , 1.34869732, 0.56798438, 2.18344354,
        0.        , 0.        , 0.        , 2.07688014, 2.1940494 ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.8990617 , 0.        , 0.56481687]])

In [170]:
W2

array([[-0.1048553 , -0.14200179, -0.17062702],
       [ 0.19507754, -0.05096522, -0.04380743],
       [-0.12527954,  0.07774904, -0.16138978],
       [-0.02127403, -0.08954666,  0.03869025],
       [-0.05108051, -0.11806322, -0.00281822],
       [ 0.04283319,  0.00665172,  0.03024719],
       [-0.06343221, -0.03627412, -0.06724604],
       [-0.03595532, -0.08131463, -0.17262826],
       [ 0.01774261, -0.04017809, -0.16301983],
       [ 0.04627823, -0.09072984,  0.00519454]])

In [171]:
step2 = np.dot(relu,W2) + b2

In [172]:
step2

array([[-0.81233741, -1.27654624, -0.70335995],
       [-0.17129677, -1.18803311, -0.47310444],
       [-0.51590475, -1.01354314, -0.8504215 ],
       [-0.15419291, -0.48629638, -0.52901952],
       [-0.00618733, -0.12435261, -0.15226949]])

In [173]:
scores = 0.

#############################################################################
# TODO: Perform the forward pass, computing the class probabilities for the #
# input. Store the result in the scores variable, which should be an array  #
# of shape (N, C).                                                          #
#############################################################################

# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

step1 = np.dot(X, W1) + b1                #(5 , 10)

for inx, el in enumerate(step1, 0):       #Relu function
    for ind2 , el2 in enumerate(el, 0):
        if el2 < 0:
            step1[inx][ind2] = 0

step2 = np.dot(step1, W2) + b2          #(5 , 3)

scores += step2 

In [174]:
scores

array([[-0.81233741, -1.27654624, -0.70335995],
       [-0.17129677, -1.18803311, -0.47310444],
       [-0.51590475, -1.01354314, -0.8504215 ],
       [-0.15419291, -0.48629638, -0.52901952],
       [-0.00618733, -0.12435261, -0.15226949]])

In [183]:
### Loss function
numerator = np.exp(scores)
numerator

array([[0.44381946, 0.27899923, 0.4949196 ],
       [0.84257149, 0.30482022, 0.62306499],
       [0.59696025, 0.36293078, 0.42723482],
       [0.85710666, 0.61489953, 0.58918237],
       [0.99383178, 0.88306841, 0.85875682]])

In [181]:
denom = np.sum(numerator, axis = 1)
denom

array([1.2177383 , 1.7704567 , 1.38712585, 2.06118856, 2.735657  ])

In [194]:
J = []
for i, score in enumerate(numerator):
    
    score_i = score[y[i]]/ denom[i]
    
    log_score_i = -np.log(score_i) 
    print(log_score_i)
    J.append(log_score_i)

JJ = np.mean(J)

1.0093326997358134
1.7592706445552908
1.1776553679162312
1.252302310512784
1.1307242378701479


In [195]:
print(J)
print(JJ)

[1.0093326997358134, 1.7592706445552908, 1.1776553679162312, 1.252302310512784, 1.1307242378701479]
1.2658570521180532


In [110]:
theLog=  - np.log(f)
theLog

array([[2.12989502, 2.17047609, 1.79968917],
       [1.48885438, 2.08196296, 1.56943366],
       [1.83346236, 1.90747299, 1.94675071],
       [1.47175052, 1.38022624, 1.62534874],
       [1.32374493, 1.01828246, 1.24859871]])

In [129]:
thelog2 = np.sum(theLog)/theLog.size
thelog2

1.666396597280801

In [132]:
# take square of differences and sum them
l2 = np.sum(np.power((W1),2)) + np.sum(np.power((W2),2))
l2 = 0.05* l2
print(l2)

0.03793083921176699


In [133]:
thelog2 + l2  #1.66 0.75

1.704327436492568